# MySQL
default: &default
  adapter: mysql2
  encoding: utf8mb4
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tapas_development

test:
  <<: *default
  database: tapas_test

production:
  primary: &primary_production
    <<: *default
    database: tapas_production
    username: <%= ENV.fetch('MYSQL_USER') %>
    password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  cache:
    <<: *primary_production
    database: tapas_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tapas_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tapas_production_cable
    migrations_paths: db/cable_migrate
